export default {
  request: "/api/v1/request",
  profile: "/api/v1/user/profile",
  getAllUsers: "/api/v1/user",
  userSearch: "/api/v1/user/search",
  getAllPermissions: "/api/v1/permission",
  searchPermissionsMapping: "/api/v1/permission/mapping/search",
  savePermissionByRole: "/api/v1/permission/mapping",
  deactivateUser: (userId) => `/api/v1/user/${userId}/deactivate`,
  activateUser: (userId) => `/api/v1/user/${userId}/activate`,
  changePassword: (userId) => `/api/v1/user/${userId}/changePassword`,
  searchTicket: `/api/v1/ticket/search`,
  resetPassword: (userId) => `/api/v1/user/${userId}/resetPassword`,
  getAllRoles: "/api/v1/role",
  deleteRole: "/api/v1/role",
  getUsersByRole: "/api/v1/role/mapping",
  roleMapping: "/api/v1/role/mapping",
  getMetaData: "/api/v1/ticket/metadata",
  getDeficiencyCategory: "/api/v1/ticket/searchDeficiencyCategory",
  getAuditData: "/api/v1/ticket/history",
  getAllTickets: "/api/v1/ticket",
  getSRReport: "/api/v1/ticket/searchServiceRequest",
  ticketDashboard: "/api/v1/ticket/dashboard",
  uploadMultipleFiles: (ticketId) => `/api/v1/uploadMultipleFiles/${ticketId}`,
  uploadMultipleInventoryFiles: (documentId) => `/api/v1/inventory/uploadMultipleFiles/${documentId}`,
  postTicketComment: "/api/v1/ticket/comment",
  postCondoComment: "/api/v1/ticket/condoComment/comment",
  postCondoRelationComment: "/api/v1/ticket/condoRelation/comment",
  postBulkTickets: "/api/v1/ticket/bulk",
  // Message api start
  getInbox: "/api/v1/message/inbox",
  getSentItems: "/api/v1/message/sendItem",
  readMessage: (messageId) => `/api/v1/message/readMessage/${messageId}`,
  // Message api end
  contactPageInfo: "/api/v1/contact",
  searchContact: "/api/v1/contact/search",
  contactMetaData: "/api/v1/contact/metaData",
  homeOwner: "/api/v1/home/owner",
  homeOwnerSearch: "/api/v1/home/owner/search",
  homeOwnerDeactivate: (ownerEmailId) => `/api/v1/home/owner/${ownerEmailId}/deactivate`,
  homeOwnerActivate: (ownerEmailId) => `/api/v1/home/owner/${ownerEmailId}/activate`,
  getDocument: "/api/v1/document",
  getInventory: "/api/v1/inventory/myInventory",
  updateInventory: "/api/v1/inventory",
  searchDeals: "/api/v1/enquiry/search",
  searchEnquiryGlobal: "/api/v1/enquiry/global/search",
  enquiry: "/api/v1/enquiry",
  enquiryNote: "/api/v1/enquiry/note",
  searchInventory: "/api/v1/inventory/search",
  myTicket: "/api/v1/ticket/myTicket",
  exportTicket: "/api/v1/ticket/report",
  exportSummaryReport: "/api/v1/ticket/report/summary",
  exportEscalationReport: "/api/v1/ticket/report/escalation",
  getAllProjects: "/api/v1/property/search",
  projectSearch: "/api/v1/project/search",
  project: "/api/v1/property",
  content: "/api/v1/content",
  getAllContents: "/api/v1/content/search",
  getSearchContents: "/api/v1/content/full/search",
  getAllUploads: "/api/v1/content/document/search",
  getActionTaken: "/api/v1/ticket/actionTaken",
  generateWorkOrder: "/api/v1/ticket/workOrder",
  getAllCategories: "/api/v1/content/category",
  vendorData: "/api/v1/ticket/workOrder",
  vendorDataReport: "/api/v1/workOrder/report",
  detailReport: "/api/v1/ticket/report/detail",
  tradeDashboardLink: "/api/v1/workOrder/dashboard",
  serviceRequestData: "/api/v1/ticket/serviceRequest",
  getAllMedia: "/api/v1/content/image/search",
  uploadMedia: "/api/v1/content/uploadImage",
  deleteMedia: "/api/v1/content/deleteImage",
  searchVendor: "/api/v1/vendor/project/search",
  deleteVendor: "/api/v1/vendor",
  deleteVendorProject: "/api/v1/vendor/project",
  searchVendorProject: "/api/v1/vendor/search",
  searchBuilding: "/api/v1/project/search/building",
  searchFloor: "/api/v1/project/search/floor",
  searchUnit: "/api/v1/project/search/unit",
  addToProject: (projectCode) => `/api/v1/vendor/${projectCode}`,
  sendWorkOrder: "/api/v1/ticket/sendWorkOrder",
  sendReportSR: "/api/v1/ticket/sendWorkOrder",
  sendServiceRequest: "/api/v1/ticket/sendServiceRequest",
  getPropertyList: "/api/v1/app/property/search",
  searchWorkOrder: "/api/v1/ticket/searchWorkOrder",
  enquiryDashboard: "/api/v1/enquiry/dashboard",
  enquiryDownload: "/api/v1/enquiry/download/csv",
  performanceAuditDownload: "/api/v1/ticket/download/performance/audit",
  enquiryDashboardSearch: "/api/v1/enquiry/dashboard/search",
  enquiryDashboardProspect: "/api/v1/enquiry/dashboard/prospect",
  noteProspect: "/api/v1/prospect/note",
  searchProspect: "/api/v1/prospect/search",
  searchAgent: "/api/v1/agent/search",
  searchBrokerage: "/api/v1/brokerage/search",
  deleteProspect: "/api/v1/prospect",
  deleteAgent: "/api/v1/agent",
  deleteBrokerage: "/api/v1/brokerage",
  updateProspect: "/api/v1/prospect",
  updateAgent: "/api/v1/agent",
  updateBrokerage: "/api/v1/brokerage",
  downloadAgentWorksheet: "/api/v1/sales/worksheet/download/csv",
  downloadTurnOverReport: "/api/v1/ticket/download/turnOver/report",
  downloadAnalyticsData: "/api/v1/campaign/analytics/clickUrl/details/download",
  subCategorySearch: "/api/v1/subCategory/search",
  subCategory: "/api/v1/subCategory",
  deleteProjectSubCategory: (projectCode) => `/api/v1/subCategory/${projectCode}`,
  deleteCategory: "/api/v1/category",
  deleteProjectCategory: (projectCode) => `/api/v1/category/${projectCode}`,
  deleteFloorCategory: (projectCode, buildingCode, floorCode) => `/api/v1/category/${projectCode}/${buildingCode}/${floorCode}`,
  addCategory: "/api/v1/category",
  addNewProjectCategory: (projectCode) => `/api/v1/category/${projectCode}`,
  addNewFloorCategory: (projectCode, buildingCode, floorCode) => `/api/v1/category/${projectCode}/${buildingCode}/${floorCode}`,
  addProjectSubCategoryData: (projectCode) => `/api/v1/subCategory/${projectCode}`,
  addSubCategory: "/api/v1/subCategory",
  categorySearch: "/api/v1/category/search",
  categoryProjectSearch: (projectCode) => `/api/v1/category/${projectCode}/search`,
  categoryBuildingSearch: (projectCode) => `/api/v1/category/search/notPresent`,
  projectSubCategorySearch: (projectCode) => `/api/v1/subCategory/${projectCode}/search`,
  agentWorksheet: "/api/v1/sales/worksheet/search",
  agentWorkSheetEvent: "/api/v1/sales/worksheet/event",
  marketingList: "/api/v1/marketing/list",
  marketingListClone: "/api/v1/marketing/list/clone",
  contactMarketingList: "/api/v1/marketing/list/contact",
  contactUploadMarketingList: "/api/v1/marketing/list/upload/contact",
  searchMarketingList: "/api/v1/marketing/list/search",
  crmMetadata: "/api/v1/crm/metadata",
  searchEmailCampaigns: "/api/v1/campaign/search",
  emailCampaigns: "/api/v1/campaign",
  uploadTemplateZIP: "/api/v1/campaign/file/uploadFile",
  uploadTemplateHTML: "/api/v1/campaign/file/uploadHtml",
  scheduleCampaigns: "/api/v1/campaign/schedule",
  campaignsSenderList: "/api/v1/sender",
  campaignsAllSenderList: "/api/v1/sender/search",
  campaignsSendTestEmail: "/api/v1/campaign/test",
  campaignStats: (campaignId) => `/api/v1/campaign/stat/${campaignId}`,
  getEmployee: "/api/v1/employee/search",
  deleteEmployee: "/api/v1/employee",
  emailContact: "/api/v1/campaign/contact/search/email",
  appointments: "/api/v1/appointment/search",
  searchInspection: "/api/v1/inspection/search",
  searchInventoryInspection: "/api/v1/inventory/inspection/search",
  searchParkingInspection: "/api/v1/parking/inspection/search",
  searchLockerInspection: "/api/v1/locker/inspection/search",
  searchParking: "/api/v1/parking/search",
  searchLocker: "/api/v1/locker/search",
  getCampaignHtml: (campaignId) => `/api/v1/campaign/public/${campaignId}`,
  addEmployee: "/api/v1/contact",
  addBrokerage: "/api/v1/brokerage",
  searchBrokerageAgent: "/api/v1/brokerage/agent/search",
  mapBrokerageAgent: "/api/v1/brokerage/agent/mapping",
  tradeTypeSearch: "/api/v1/vendor/search/tradeType",
  getTenantDetails: "/api/v1/tenant",
  tenantSearch: "/api/v1/tenant/search",
  downloadTicketFile: (ticketId, fileName) => `/api/v1/downloadFile/${ticketId}/${fileName}`,
  deleteTicketFile: (ticketId, fileName) => `/api/v1/deleteFile/${ticketId}/${fileName}`,
  getBuilding: "/api/v1/building/search",
  saveBuilding: "/api/v1/building",
  getCatgeoryNew: () => `/api/v1/category/search`,
  uploadPerformanceAudit: "/api/v1/ticket/uploadPerformanceAudit",
  purchaserWorkSheet: "/api/v1/sales/worksheet/search/prospect",
  deleteWorkSheet: "/api/v1/sales/worksheet",
  searchRole: "/api/v1/role/search",
  marketingListDownload: "/api/v1/marketing/list/download/contact",
  campaignAnalytics: "/api/v1/campaign/contact/campaign/analytics",
  searchEmail: "/api/v1/email/search",
  composeEmail: "/api/v1/email/compose/send",
  campaignAnalyticsClickUrl: "/api/v1/campaign/analytics/clickUrl",
  searchLetter: "/api/v1/letter/search",
  campaignAnalyticsClickUrlDetails: "/api/v1/campaign/analytics/clickUrl/details",
  pdiReportDownload: '/api/v1/ticket/pdi/report',
  supplementaryReport: `/api/v1/ticket/pdi/supplementary/report`,
  campaignClone: "/api/v1/campaign/clone",
  projectMock: "/api/v2/project/search",
  salesProjectSearch: "/api/v1/sales/project/search",
  lotSearch: "/api/v1/sales/unit/search",
  lotDocumentSearch: "/api/v1/sales/unit/document/search",
  uploadLotDocuments: (unitCode) => `/api/v1/sales/unit/document/uploadFile/${unitCode}`,
  contractSummarySearch: "/api/v2/contractsummary/search",
};
