name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm install --legacy-peer-deps
          npx nx run-many -t test --codeCoverage -p core cms scripts web-react ui-material-base integration-test
          npx nx run-many -t dist -p core scripts cms web-react ui-material-base
